/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing_nov_6th.db123testing.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing_nov_6th.db123testing.NewTypesUser;


/**
 * ServiceImpl object for domain model class NewTypesUser.
 *
 * @see NewTypesUser
 */
@Service("DB123Testing.NewTypesUserService")
@Validated
public class NewTypesUserServiceImpl implements NewTypesUserService {

    private static final Logger LOGGER = LoggerFactory.getLogger(NewTypesUserServiceImpl.class);


    @Autowired
    @Qualifier("DB123Testing.NewTypesUserDao")
    private WMGenericDao<NewTypesUser, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<NewTypesUser, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "DB123TestingTransactionManager")
    @Override
	public NewTypesUser create(NewTypesUser newTypesUser) {
        LOGGER.debug("Creating a new NewTypesUser with information: {}", newTypesUser);
        NewTypesUser newTypesUserCreated = this.wmGenericDao.create(newTypesUser);
        return newTypesUserCreated;
    }

	@Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
	public NewTypesUser getById(Integer newtypesuserId) throws EntityNotFoundException {
        LOGGER.debug("Finding NewTypesUser by id: {}", newtypesuserId);
        NewTypesUser newTypesUser = this.wmGenericDao.findById(newtypesuserId);
        if (newTypesUser == null){
            LOGGER.debug("No NewTypesUser found with id: {}", newtypesuserId);
            throw new EntityNotFoundException(String.valueOf(newtypesuserId));
        }
        return newTypesUser;
    }

    @Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
	public NewTypesUser findById(Integer newtypesuserId) {
        LOGGER.debug("Finding NewTypesUser by id: {}", newtypesuserId);
        return this.wmGenericDao.findById(newtypesuserId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "DB123TestingTransactionManager")
	@Override
	public NewTypesUser update(NewTypesUser newTypesUser) throws EntityNotFoundException {
        LOGGER.debug("Updating NewTypesUser with information: {}", newTypesUser);
        this.wmGenericDao.update(newTypesUser);

        Integer newtypesuserId = newTypesUser.getId();

        return this.wmGenericDao.findById(newtypesuserId);
    }

    @Transactional(value = "DB123TestingTransactionManager")
	@Override
	public NewTypesUser delete(Integer newtypesuserId) throws EntityNotFoundException {
        LOGGER.debug("Deleting NewTypesUser with id: {}", newtypesuserId);
        NewTypesUser deleted = this.wmGenericDao.findById(newtypesuserId);
        if (deleted == null) {
            LOGGER.debug("No NewTypesUser found with id: {}", newtypesuserId);
            throw new EntityNotFoundException(String.valueOf(newtypesuserId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
	public Page<NewTypesUser> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all NewTypesUsers");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "DB123TestingTransactionManager")
    @Override
    public Page<NewTypesUser> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all NewTypesUsers");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "DB123TestingTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service DB123Testing for table NewTypesUser to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "DB123TestingTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

