/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing_nov_6th.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing_nov_6th.salesdb.Sample;


/**
 * ServiceImpl object for domain model class Sample.
 *
 * @see Sample
 */
@Service("salesdb.SampleService")
@Validated
public class SampleServiceImpl implements SampleService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SampleServiceImpl.class);


    @Autowired
    @Qualifier("salesdb.SampleDao")
    private WMGenericDao<Sample, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Sample, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "salesdbTransactionManager")
    @Override
	public Sample create(Sample sample) {
        LOGGER.debug("Creating a new Sample with information: {}", sample);
        Sample sampleCreated = this.wmGenericDao.create(sample);
        return sampleCreated;
    }

	@Transactional(readOnly = true, value = "salesdbTransactionManager")
	@Override
	public Sample getById(Integer sampleId) throws EntityNotFoundException {
        LOGGER.debug("Finding Sample by id: {}", sampleId);
        Sample sample = this.wmGenericDao.findById(sampleId);
        if (sample == null){
            LOGGER.debug("No Sample found with id: {}", sampleId);
            throw new EntityNotFoundException(String.valueOf(sampleId));
        }
        return sample;
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
	@Override
	public Sample findById(Integer sampleId) {
        LOGGER.debug("Finding Sample by id: {}", sampleId);
        return this.wmGenericDao.findById(sampleId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "salesdbTransactionManager")
	@Override
	public Sample update(Sample sample) throws EntityNotFoundException {
        LOGGER.debug("Updating Sample with information: {}", sample);
        this.wmGenericDao.update(sample);

        Integer sampleId = sample.getId();

        return this.wmGenericDao.findById(sampleId);
    }

    @Transactional(value = "salesdbTransactionManager")
	@Override
	public Sample delete(Integer sampleId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Sample with id: {}", sampleId);
        Sample deleted = this.wmGenericDao.findById(sampleId);
        if (deleted == null) {
            LOGGER.debug("No Sample found with id: {}", sampleId);
            throw new EntityNotFoundException(String.valueOf(sampleId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "salesdbTransactionManager")
	@Override
	public Page<Sample> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Samples");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<Sample> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Samples");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service salesdb for table Sample to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "salesdbTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

