/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing_nov_6th.db123testing.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.hibernate.TypeMismatchException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.testing_nov_6th.db123testing.NewTypesUser;
import com.testing_nov_6th.db123testing.service.NewTypesUserService;


/**
 * Controller object for domain model class NewTypesUser.
 * @see NewTypesUser
 */
@RestController("DB123Testing.NewTypesUserController")
@Api(value = "NewTypesUserController", description = "Exposes APIs to work with NewTypesUser resource.")
@RequestMapping("/DB123Testing/NewTypesUser")
public class NewTypesUserController {

    private static final Logger LOGGER = LoggerFactory.getLogger(NewTypesUserController.class);

    @Autowired
	@Qualifier("DB123Testing.NewTypesUserService")
	private NewTypesUserService newTypesUserService;

	@ApiOperation(value = "Creates a new NewTypesUser instance.")
@RequestMapping(method = RequestMethod.POST, consumes = "multipart/form-data")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
public NewTypesUser createNewTypesUser(@RequestPart("wm_data_json") NewTypesUser newTypesUser, @RequestPart(value = "blobCol", required = false) MultipartFile _blobCol) {
		LOGGER.debug("Create NewTypesUser with information: {}" , newTypesUser);

    newTypesUser.setBlobCol(WMMultipartUtils.toByteArray(_blobCol));
		newTypesUser = newTypesUserService.create(newTypesUser);
		LOGGER.debug("Created NewTypesUser with information: {}" , newTypesUser);

	    return newTypesUser;
	}

    @ApiOperation(value = "Returns the NewTypesUser instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public NewTypesUser getNewTypesUser(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting NewTypesUser with id: {}" , id);

        NewTypesUser foundNewTypesUser = newTypesUserService.getById(id);
        LOGGER.debug("NewTypesUser details with id: {}" , foundNewTypesUser);

        return foundNewTypesUser;
    }

    @ApiOperation(value = "Retrieves content for the given BLOB field in NewTypesUser instance" )
    @RequestMapping(value = "/{id}/content/{fieldName}", method = RequestMethod.GET, produces="application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public DownloadResponse getNewTypesUserBLOBContent(@PathVariable("id") Integer id, @PathVariable("fieldName") String fieldName, HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, @RequestParam(value="download", defaultValue = "false") boolean download) {

        LOGGER.debug("Retrieves content for the given BLOB field {} in NewTypesUser instance" , fieldName);

        if(!WMRuntimeUtils.isLob(NewTypesUser.class, fieldName)) {
            throw new TypeMismatchException("Given field " + fieldName + " is not a valid BLOB type");
        }
        NewTypesUser newTypesUser = newTypesUserService.getById(id);

        return WMMultipartUtils.buildDownloadResponseForBlob(newTypesUser, fieldName, httpServletRequest, download);
    }

    @ApiOperation(value = "Updates the NewTypesUser instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public NewTypesUser editNewTypesUser(@PathVariable("id") Integer id, @RequestBody NewTypesUser newTypesUser) throws EntityNotFoundException {
        LOGGER.debug("Editing NewTypesUser with id: {}" , newTypesUser.getId());

        newTypesUser.setId(id);
        newTypesUser = newTypesUserService.update(newTypesUser);
        LOGGER.debug("NewTypesUser details with id: {}" , newTypesUser);

        return newTypesUser;
    }

    @ApiOperation(value = "Updates the NewTypesUser instance associated with the given id.This API should be used when NewTypesUser instance fields that require multipart data.") 
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.POST, consumes = {"multipart/form-data"})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public NewTypesUser editNewTypesUser(@PathVariable("id") Integer id, MultipartHttpServletRequest multipartHttpServletRequest) throws EntityNotFoundException {
        NewTypesUser newNewTypesUser = WMMultipartUtils.toObject(multipartHttpServletRequest, NewTypesUser.class, "DB123Testing");
        newNewTypesUser.setId(id);

        NewTypesUser oldNewTypesUser = newTypesUserService.getById(id);
        WMMultipartUtils.updateLobsContent(oldNewTypesUser, newNewTypesUser);
        LOGGER.debug("Updating NewTypesUser with information: {}" , newNewTypesUser);

        return newTypesUserService.update(newNewTypesUser);
    }

    @ApiOperation(value = "Deletes the NewTypesUser instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteNewTypesUser(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting NewTypesUser with id: {}" , id);

        NewTypesUser deletedNewTypesUser = newTypesUserService.delete(id);

        return deletedNewTypesUser != null;
    }

    /**
     * @deprecated Use {@link #findNewTypesUsers(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of NewTypesUser instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<NewTypesUser> searchNewTypesUsersByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering NewTypesUsers list");
        return newTypesUserService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of NewTypesUser instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<NewTypesUser> findNewTypesUsers(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering NewTypesUsers list");
        return newTypesUserService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of NewTypesUser instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<NewTypesUser> filterNewTypesUsers(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering NewTypesUsers list");
        return newTypesUserService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
    @RequestMapping(value = "/export/{exportType}", method = {RequestMethod.GET,  RequestMethod.POST}, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportNewTypesUsers(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return newTypesUserService.export(exportType, query, pageable);
    }

	@ApiOperation(value = "Returns the total count of NewTypesUser instances matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
	@RequestMapping(value = "/count", method = {RequestMethod.GET, RequestMethod.POST})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countNewTypesUsers( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting NewTypesUsers");
		return newTypesUserService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getNewTypesUserAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return newTypesUserService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service NewTypesUserService instance
	 */
	protected void setNewTypesUserService(NewTypesUserService service) {
		this.newTypesUserService = service;
	}

}

